spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 'g2XYru5Q'
  redis:
    database: 0
    host: localhost
