spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: score.reorz.com
    password: ko0oD59XJC34d2Putt6e
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    #org.hibernate.type.descriptor.ql.BasicBinder: TRACE
    org.hibernate.engine.QueryParameters: DEBUG
    org.hibernate.engine.query.HQLQueryPlan: DEBUG
    org.hibernate.SQL: DEBUG
